on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the main branch

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials for EKS (Production Environment)
      - name: Configure AWS Credentials for Production
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      # Install kubectl for interacting with EKS
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Set the image for the deployment in EKS (Production)
      - name: Update EKS Production Deployment
        run: |
          kubectl set image deployment/your-deployment your-container=your-docker-repo/your-image-name:${{ github.sha }}
          kubectl rollout status deployment/your-deployment
